### ISSUE TITLE
No collection after creating first user

### ISSUE THREAD

**Issue by aprilcoskun** [parkuman/pocketcms#6]
I can't see any collection after creating the first user for cms. Also there is no collection creation option.
<img width="880" alt="image" src="https://github.com/user-attachments/assets/9de9dd1d-7fb3-4c25-802c-9dc32ec82539">

**Comment by parkuman** [comment]
Hi Nisan!

Can you check in PocketBase the API rules for the collection you wish to modify from PocketCMS?

<img width="697" alt="Screenshot 2024-07-22 at 16 58 22" src="https://github.com/user-attachments/assets/fb6e6170-f0c2-49b2-a57e-142ceac635eb">

If the view rule is set to admins only, the user logged into PocketCMS won't be able to see it since they aren't an admin of PocketBase. In addition, a user in PocketCMS can't create a new collection, that is something that should be done from within PocketBase. 

There is some more work to be done on permissions in the future so that you don't have to completely open up the API rules to anyone in order for PocketCMS to work. The ticket is in the project dashboard if anyone is interested in picking it up!

**Comment by aprilcoskun** [comment]
Thanks, that solved the issue, now I can see the collections.
I have another question. Every user can see same data on the collection. Can we have multitenancy?

**Comment by parkuman** [comment]
> Thanks, that solved the issue, now I can see the collections. I have another question. Every user can see same data on the collection. Can we have multitenancy?

That would be a great feature. I’ll add it to the list of ideas and try to tackle it in the near future! 

Any other questions feel free to send them here or to parker@prowe.ca! Thanks for checking out the project :)
